name: CoachFeed

on:
  push:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

# Repo-level permission hint: Settings → Actions → Workflow permissions → Read and write
permissions:
  contents: read
  issues: write

jobs:
  coach:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with history for diffs
        uses: actions/checkout@v4
        with:
          fetch-depth: 20

      - name: Detect stacks
        id: detect
        run: |
          echo "has_node=false" >> $GITHUB_OUTPUT
          echo "has_python=false" >> $GITHUB_OUTPUT
          [ -f package.json ] && echo "has_node=true" >> $GITHUB_OUTPUT
          { [ -f requirements.txt ] || ls -1 **/requirements.txt 2>/dev/null; } && echo "has_python=true" >> $GITHUB_OUTPUT

      - name: Setup Node
        if: steps.detect.outputs.has_node == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Python
        if: steps.detect.outputs.has_python == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Node deps
        if: steps.detect.outputs.has_node == 'true'
        continue-on-error: true
        run: |
          if [ -f package-lock.json ]; then npm ci || npm install; else npm install || true; fi

      - name: Install Python deps
        if: steps.detect.outputs.has_python == 'true'
        continue-on-error: true
        run: |
          [ -f requirements.txt ] && pip install -r requirements.txt || true
          # Ensure pytest if tests exist
          if [ -d tests ] || ls -1 **/tests 2>/dev/null; then
            python - <<'PY'
import importlib, subprocess, sys
try: importlib.import_module("pytest")
except ImportError: subprocess.check_call([sys.executable, "-m", "pip", "install", "pytest"])
PY
          fi

      - name: Build diff summary
        id: diff
        run: |
          set -e
          if [ "${{ github.event_name }}" = "push" ]; then
            BEFORE="${{ github.event.before }}"; AFTER="${{ github.event.after }}"
            if [ "$BEFORE" = "0000000000000000000000000000000000000000" ] || [ -z "$BEFORE" ]; then
              RANGE="HEAD~1..HEAD"
            else
              RANGE="$BEFORE..$AFTER"
            fi
          else
            git fetch --all --prune
            A=$(git rev-parse HEAD); B=$(git rev-parse HEAD~1); RANGE="$B..$A"
          fi

          {
            echo "## Changed files"
            echo '```'
            git diff --name-only $RANGE || true
            echo '```'

            echo
            echo "## Short diff (first 200 lines)"
            echo '```diff'
            git diff --unified=1 $RANGE | head -n 200 || true
            echo '```'
          } > coach_summary.md

      - name: Node diagnostics
        if: steps.detect.outputs.has_node == 'true'
        continue-on-error: true
        run: |
          {
            echo; echo "## Node diagnostics"
            echo '```bash'; node -v || true; npm -v || true; echo '```'

            echo; echo "### npm test"
            echo '```'
            npm test --silent --if-present || true
            echo '```'

            echo; echo "### npm run lint"
            echo '```'
            npm run lint --silent --if-present || true
            echo '```'

            echo; echo "### npm run build"
            echo '```'
            npm run build --silent --if-present || true
            echo '```'
          } >> coach_summary.md

      - name: Python diagnostics
        if: steps.detect.outputs.has_python == 'true'
        continue-on-error: true
        run: |
          {
            echo; echo "## Python diagnostics"
            echo '```bash'; python --version || true; pip --version || true; echo '```'
            if [ -d tests ] || ls -1 **/tests 2>/dev/null; then
              echo; echo "### pytest"
              echo '```'; pytest -q || true; echo '```'
            fi
            # flake8 only if available
            python - <<'PY' >/dev/null 2>&1 || true
import importlib, sys; sys.exit(0 if importlib.util.find_spec("flake8") else 1)
PY
            if [ $? -eq 0 ]; then
              echo; echo "### flake8"
              echo '```'; flake8 || true; echo '```'
            fi
          } >> coach_summary.md

      - name: Footer
        run: |
          {
            echo
            echo "---"
            echo "Repo: ${{ github.repository }}"
            echo "Ref: ${{ github.ref }}"
            echo "Run: ${{ github.run_id }}"
            echo "Event: ${{ github.event_name }}"
            echo "Time: $(date -u +"%Y-%m-%d %H:%M:%S") UTC"
          } >> coach_summary.md

      - name: Find or create Coach Feed issue
        id: issue
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo;
            const title = "Coach Feed";
            const res = await github.rest.search.issuesAndPullRequests({
              q: `repo:${owner}/${repo} is:issue in:title "${title}" state:open`
            });
            let number;
            if (res.data.total_count) {
              number = res.data.items[0].number;
            } else {
              const created = await github.rest.issues.create({
                owner, repo, title, body: "Automated diagnostics stream. Pin this issue for easy access."
              });
              number = created.data.number;
            }
            core.setOutput("number", String(number));

      - name: Post comment to issue
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: Number("${{ steps.issue.outputs.number }}"),
              body: fs.readFileSync('coach_summary.md','utf8')
            });
